# Generated by Django 5.2.17 on 2026-09-19 19:14

from django.db import migrations

SKILL_LIST = [
    {"name": "Python", "icon_url": "https://cdn.simpleicons.org/python"},
    {"name": "JavaScript", "icon_url": "https://cdn.simpleicons.org/javascript"},
    {"name": "TypeScript", "icon_url": "https://cdn.simpleicons.org/typescript"},
    {"name": "React", "icon_url": "https://cdn.simpleicons.org/react"},
    {"name": "Next.js", "icon_url": "https://cdn.simpleicons.org/nextdotjs"},
    {"name": "Django", "icon_url": "https://cdn.simpleicons.org/django"},
    {"name": "Supabase", "icon_url": "https://cdn.simpleicons.org/supabase"},
    {"name": "Docker", "icon_url": "https://cdn.simpleicons.org/docker"},
    {"name": "Git", "icon_url": "https://cdn.simpleicons.org/git"},
    {"name": "Figma", "icon_url": "https://cdn.simpleicons.org/figma"},
    {"name": "Notion", "icon_url": "https://cdn.simpleicons.org/notion"},
    {"name": "Jira", "icon_url": "https://cdn.simpleicons.org/jira"},
]


def seed_skills(apps, schema_editor):
    Skill = apps.get_model("main", "Skill")
    Skill.objects.bulk_create(
        [Skill(name=skill["name"], icon_url=skill["icon_url"]) for skill in SKILL_LIST]
    )


def remove_seeded_skills(apps, schema_editor):
    Skill = apps.get_model("main", "Skill")
    Skill.objects.filter(name__in=[skill["name"] for skill in SKILL_LIST]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill'),
    ]

    operations = [
        migrations.RunPython(seed_skills, remove_seeded_skills),
    ]
