# Generated by Django 5.2.17

from django.db import migrations

CATEGORY_BY_NAME = {
    "Python": "Technology",
    "JavaScript": "Technology",
    "TypeScript": "Technology",
    "React": "Technology",
    "Next.js": "Technology",
    "Django": "Technology",
    "Supabase": "Technology",
    "Docker": "Technology",
    "Git": "Tools",
    "Figma": "Tools",
    "Notion": "Tools",
    "Jira": "Tools",
}


def set_skill_categories(apps, schema_editor):
    Skill = apps.get_model("main", "Skill")
    for name, category in CATEGORY_BY_NAME.items():
        Skill.objects.filter(name=name).update(category=category)


def unset_skill_categories(apps, schema_editor):
    Skill = apps.get_model("main", "Skill")
    Skill.objects.filter(name__in=CATEGORY_BY_NAME.keys()).update(category="")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_seed_skill_data'),
    ]

    operations = [
        migrations.RunPython(set_skill_categories, unset_skill_categories),
    ]
